### PR TITLE
Added links to github packages/reorganized tables

### PR DESCRIPTION
**Pull request by sboldyreva**

### CODE REVIEW

**Comment by bennyvasquez** [comment]
Hey @sboldyreva! This is a great start, but the first thing I noticed is that you're using HTML instead of markdown here. Is there a reason for the switch? I really want to keep things in markdown in the wiki.

**Comment by sboldyreva** [comment]
@bennyvasquez yes, let me show it with a screenshot. From my point of view, with new links markdown tables look a bit messy. So I thought of using united cells to make it more "easy to read", but as markdown can't really help here, I used HTML 
image

**Comment by bennyvasquez** [comment]
AH! That makes a lot of sense. I think we could make the table a bit more concise maybe, and accomplish the same thing. Is there a benefit to having the link separate rather than having the word link to the destination? For example:

| AlmaLinux Version  | DockerHub | Quay.io |
| ------------- | ------------- | ----- |
| 8  | [Docker Hub](hub.docker.com/r/almalinux/8-minimal) | [Quay.io](https://quay.io/repository/almalinuxorg/8-minimal?tab=tags)|
| 9  | [Docker Hub](hub.docker.com/r/almalinux/9-minimal) | [Quay.io](https://quay.io/repository/almalinuxorg/9-minimal?tab=tags) |

**Comment by sboldyreva** [comment]
I don't really fancy having platforms as links too, it looks a bit "too much" for me. But maybe listing versions then will make a better option? It still uses the `<br>` HTML element though, but the table itself is markdown. @bennyvasquez @andrewlukoshko 
```
| Platform | AlmaLinux Version |
| --- | --- |
| Docker Hub |  [8]()<br>[9]() | 
| Quay.io |  [8]()<br>[9]() |
| GitHub Packages |  [8]()<br>[9]() |
```

Which render as:
| Platform | AlmaLinux Version |
| --- | --- |
| Docker Hub |  [8]()<br>[9]() | 
| Quay.io |  [8]()<br>[9]() |
| GitHub Packages |  [8]()<br>[9]() |

**Comment by bennyvasquez** [comment]
The '8' and '9' links would be pretty easily missed, depending on the screen. How about listing it with 'AlmaLinux'? 

```
| Platform | Version |
| --- | --- |
| Docker Hub |  [AlmaLinux 8]()<br>[AlmaLinux9]() | 
| Quay.io |  [AlmaLinux 8]()<br>[AlmaLinux 9]() |
| GitHub Packages |  [AlmaLinux 8]()<br>[AlmaLinux 9]() |
```

Which render as:
| Platform | AlmaLinux Version |
| --- | --- |
| Docker Hub |  [AlmaLinux 8]()<br>[AlmaLinux 9]() | 
| Quay.io |  [AlmaLinux 8]()<br>[AlmaLinux 9]() |
| GitHub Packages |  [AlmaLinux 8]()<br>[AlmaLinux 9]() |

**Comment by sboldyreva** [comment]
@bennyvasquez agreed and updated

**Review by bennyvasquez — APPROVED** [review]
YAY! Thanks for the discussion on this one. <3

**Pull request merged**
