### PR TITLE
Add FAQ item for bug fix contributions

### PR DESCRIPTION
**Pull request by carlwgeorge**
Howdy AlmaLinux team!  Congrats on your recent release.

I spoke with Jack on [Reddit](https://old.reddit.com/r/CentOS/comments/m65r4x/the_centos_survey/grbllvf/?context=3) about potential collaboration opportunities in the future between AlmaLinux and CentOS.  I think an FAQ item like this would be a good first step.  I'm happy to adjust the phrasing if needed.

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Conan-Kudo** [comment]
This looks great. As a Fedora/CentOS contributor who'll also be using AlmaLinux too, I really welcome this! 💯

**Comment by ezamriy** [comment]
Carl, thanks for bringing this up. We are definitely like the idea of cooperation.

We are going to propose a couple of additions/clarifications to the text next week. For example, it would be better to submit AlmaLinux-specific things (e.g. branding) to our projects first, and then we will try to submit them upstream if it is possible/acceptable.

**Comment by carlwgeorge** [comment]
Sure, that makes sense.  Perhaps a complete contribution guide would work better than a single FAQ item.

**Comment by carlwgeorge** [comment]
@ezamriy I can rephrase this pull request, but where should the answer send people who want to contribute to Alma-only packages?  I don't see anything resembling spec files in the [AlmaLinux org](https://github.com/AlmaLinux).

**Comment by ezamriy** [comment]
@carlwgeorge it would be great. I've asked @jaboutboul to help me finding the right words, but he is a bit busy now. Basically, I think the following things should be firstly submitted to us:

- AlmaLinux branding related issues
- AlmaLinux specific issues like our OpenScap profiles, shim, etc or AlmaLinux support in various cloud-related things like cloud-init (I'm pretty sure we can patch them ahead of upstream to improve user's experience and submit changes to upstream in parallel).

For now the only one way to submit us patches is the bugs.almalinux.org tracker. We are working on setting up a publicly accessible artifact storage and git repositories, I will update the Wiki when it's done. The Contribution Guide will become a part of this process.

**Comment by jaboutboul** [comment]
Hey @carlwgeorge Just wanted to updated you that I'm working on the language here and we should have it tamped down by next week. Like @ezamriy said we are working on the publicly available toolchain and we'll release a contributor's guide with that as well that will give detail about all the relevant pieces of info.

**Review by srbala — APPROVED** [review]
LGTM

**Comment by carlwgeorge** [comment]
Since the Alma-only packages sources are still not available, I rephrased this question to only be for bugs that also exist in RHEL.  This should be mergeable as is, and once the Alma-only packages sources are available a separate question can be added to describe contributing to them.

**Pull request merged**
