### PR TITLE
AlmaLinux/build-system#67: Create a public documentation and related …

### PR DESCRIPTION
**Pull request by soksanichenko**
…repositories for building AL by a simple user

- Add the page to config.js
- New instruction

### CODE REVIEW

**Comment by bennyvasquez** [comment]
@andrewlukoshko @soksanichenko are we held up on this for any reason? Is it ready to merge? If not, let's convert it to draft so we know it's not ready for merging.

**Comment by sboldyreva** [comment]
@bennyvasquez @soksanichenko 
It was a bit rewritten and published before
https://github.com/AlmaLinux/wiki/pull/337

**Comment by bennyvasquez** [comment]
Okay! Does that mean we should close this PR without merging, @soksanichenko / @sboldyreva?

**Comment by soksanichenko** [comment]
I closed. Thank you!

**Pull request closed without merging**
