### PR TITLE
[UPDATED] Reorganization and Simplification of Wiki Structure & Navigation.

### PR DESCRIPTION
**Pull request by xsub**
We have earlier identified that our wiki's navigation requires improvement for a more user-friendly experience. This proposal outlines ~the~ a plan to enhance navigation by introducing a more concise, alphabetically ordered structure.

Actions taken (original)
    * Regrouped to have minimal number of entities
    * Introduced alphabetical order in all but last levels of the TOC (tree)
       (It made Contribution and Development move to the top, but we want these to be visible;
       "The Foundation" - reusing `The` made allowed to sort it properly)
    * Installation & Migration are so important we want them distinct
    * Documentation has undergone a major change
    * Introduced Howto Series and previous Howtos were renamed
      ('External Howtos' at first, but then added 'Some' to sort it)
    * Security Guides are a separate sub-category now
    * Renamed Cloud to Cloud Images
    * Considered combining Cloud Images and Containers (looked bad) 
    
 Additional changes (latest update)
  * About AlmaLinux Wiki -> About, moved 2 sections to "The Foundation" (transparency & license) 
  * Added "AlmaLinux Delta" to have Errata pretty early in the sidebar
  UPDATE: AlmaLinux Delta was replaced with "Changelog & Errata";
  * Contribute menu encapsulates pieces that were scattered around - probably needs to be converted to grouping menu as now it is only expanding and not collapsing automatically.
  UPDATE: Contribute menu is now a grouping its original contents and Mirrors (as Andrew suggested).
  * Added pages /cloud & /containers so that the grouping menus are in bold. 
  * All menu and submenus are now alphabetically sorted"
  * Sub-menus that are groups are at the bottom of parent menu item, this looks/works better.
    -> the Howto Series is not populated but it will be properly displayed as grouping menu.
  * Rel. Notes moved to Documentation to match RHEL
  * MANY CHANGES to make it work/look more naturally

Preview: https://purplemanul.puffyclouds.xyz

### CODE REVIEW

**Comment by bennyvasquez** [comment]
Gonna hold on this one 'till after the 9.2 release.

**Review by bennyvasquez — APPROVED** [review]
Looks good to me!

**Comment by andrewlukoshko** [comment]
LGTM

**Comment by bennyvasquez** [comment]
Merging in!

**Pull request merged**
