### PR TITLE
Added new links to HowTo.md

### PR DESCRIPTION
**Pull request by neilasmyth**
Added new links to the HowTo wiki page

### CODE REVIEW

**Comment by bennyvasquez** [comment]
Hi @neilasmyth! It's insane how long it's taken me to get to this, and I sincerely apologize there. We don't have official guidelines for what we do and don't include yet, and looking at your website the only thing I think I'd like to see here is dates on your blog posts. Is that something you'd be willing to add?

**Comment by neilasmyth** [comment]
Hi Benny,

Thank you for the message. I appreciate you taking the time to review this. 

As requested, we’ve updated the AlmaLinux posts on the website to include the content post date. 

Please let me know if this looks OK or if you’d like to see any additional changes.

Thanks again,

Neil

**Comment by bennyvasquez** [comment]
Thanks, Neil! I checked a couple ([this one](https://www.answertopia.com/almalinux/almalinux-remote-desktop-access-with-vnc/) and [this one](https://www.answertopia.com/almalinux/displaying-almalinux-applications-remotely-x11-forwarding/)) and I'm not seeing the dates displayed. Can you check on those for me? It's possible I'm just not looking in the right place.

**Comment by neilasmyth** [comment]
Hi Benny, 

It looks like it was a caching issue. We’ve just cleared the cache, so hopefully, you will see the “Posted” date beneath the page titles. Let me know if you still aren’t seeing it and I’ll dig a little deeper. 

Thanks 

Neil

**Review by bennyvasquez — APPROVED** [review]
Perfect! Thanks so much for your patience and for the adjustment.

**Pull request merged**
