### PR TITLE
Adding kickstart guide

### PR DESCRIPTION
**Pull request by sandorex**
Adding simple kickstart guide that should help the user start and guide them towards official documentation for pykickstart project

### CODE REVIEW

**Comment by codyro** [comment]
We need a kickstart guide, and this is a good start. Can you adjust this to be AlmaLinux-specific instead of repurposing the Fedora example?

If you like, I can do this--just let me know!

**Comment by sandorex** [comment]
> Can you adjust this to be AlmaLinux-specific instead of repurposing the Fedora example?

Is there anything AlmaLinux specific to the kickstart files? I was not aware, feel free to modify it

**Comment by codyro** [comment]
I am so sorry! When I glanced at the kickstart the other day, I saw the EPEL portion and mistakingly assumed you copied/pasted it with the fedora installation media. 

I'll loop back around to this so we can get it published/flush it out more. 

Thanks!

**Comment by sej7278** [comment]
I've got a bunch of examples here too: https://github.com/sej7278/virt-installs

**Review by bennyvasquez — APPROVED** [review]

**Comment by bennyvasquez** [comment]
Thanks for your patience, @sandorex!

**Pull request merged**
