### PR TITLE
Update Comparison table

### PR DESCRIPTION
**Pull request by andrewlukoshko**
Updated:
- Release delays
- ppc64le and s390x support
- https://github.com/AlmaLinux/wiki/issues/236

comparison

### CODE REVIEW

**Review by jonathanspw — APPROVED** [review]
lgtm

**Review by jonathanspw — COMMENTED** [review]
What if we keep s390 in parentheses perhaps?  The info needs to be found for people searching for it either way.

**Review by jonathanspw — CHANGES_REQUESTED** [review]
What if we keep s390 in parentheses perhaps? The info needs to be found for people searching for it either way.

**Comment by andrewlukoshko** [comment]
@jonathanspw updated
comparison2

**Review by jonathanspw — APPROVED** [review]
Lgtm

**Pull request merged**
