### PR TITLE
Update Azure marketplace image links

### LINKED ISSUE #312: Azure marketplace link to official image is broken
The following link is broken:
https://github.com/AlmaLinux/wiki/blob/853137cbd73a65f618ee90afbd3d7391736498e9/docs/cloud/Azure.md?plain=1#L25

Should it be this : https://azuremarketplace.microsoft.com/en-us/marketplace/apps/almalinux.almalinux-x86_64?tab=Overview ?

### PR DESCRIPTION
**Pull request by codyro**
Resolves #312

### CODE REVIEW

**Comment by codyro** [comment]
Looking at the page, we should probably update the example image too?

`az vm create -n MyVm -g MyResourceGroup --image almalinux:almalinux:8_4:8.4.20210729`

**Comment by LKHN** [comment]
The new CLI examples would be:

AlmaLinux OS 8 x86_64:

```sh
az vm create -n MyVm -g MyResourceGroup --image almalinux:almalinux-x86_64:8-gen1:latest
az vm create -n MyVm -g MyResourceGroup --image almalinux:almalinux-x86_64:8-gen2:latest
```
AlmaLinux OS 9 x86_64:

```sh
az vm create -n MyVm -g MyResourceGroup --image almalinux:almalinux-x86_64:9-gen1:latest
az vm create -n MyVm -g MyResourceGroup --image almalinux:almalinux-x86_64:9-gen2:latest
```
AlmaLinux OS 8 AArch64:

```sh
az vm create -n MyVm -g MyResourceGroup --image almalinux:almalinux-arm:8-arm-gen2:latest
```
AlmaLinux OS 9 AArch64:
```sh
az vm create -n MyVm -g MyResourceGroup --image almalinux:almalinux-arm:9-arm-gen2:latest
```

**Comment by andrewlukoshko** [comment]
@codyro ^^

**Comment by codyro** [comment]
Ack, will fix it up so we can get it merged.

**Comment by bennyvasquez** [comment]
@codyro pinging in case it's fallen off your list. <3

**Comment by codyro** [comment]
Adjusted accordingly: https://github.com/AlmaLinux/wiki/pull/313/files#diff-d8e14f8b6216a0d6c5834e74f70f9ea204a1afc83f31a5ddc14269c9d921b721R42-R65

**Comment by bennyvasquez** [comment]
Sweet! @LKHN @andrewlukoshko how's this look to y'all?

**Comment by LKHN** [comment]
> Sweet! @LKHN @andrewlukoshko how's this look to y'all?

LGTM.

**Review by bennyvasquez — APPROVED** [review]

**Pull request merged**
